Feat/swarvy
h-beeen/Arcade42 pull request #149
Opened 2023-05-26 01:46 UTC by SWARVY

# Describe your changes

## Checklist

문제번호 1 : 1620 (나는야 포켓몬마스터 이다솜)
문제번호 2 : 19583 (싸이버개강총회)

- [x] 🤔 백준/프로그래머스에서 **성공입니다!** 판정을 받은 문제인가요?
- [x] 🤔 PR하기 전에 스스로 코드에 문제가 없음을 확인했나요?
- [x] 🤔 필요한 주석을 필요한 곳에 넣어주었나요?

## Questions

- 💬 [풀지 못했거나, 질문이 있다면] 자유롭게 코드에 대해 질문해주세요.
  

- 🤷‍♂️ 확인 받고 싶은 부분이에요!
  
  
- 🔥 이건 꼭 확인해주세요!

2023-05-26 14:15 UTC, rheefine commented on 현호/7주차_1620.js
> +solve();
eol 처리가 안되어있네여 ㅎ

2023-05-26 14:15 UTC, rheefine commented on 현호/7주차_19583.js
> +      const curr = time.split(":").map(Number).reduce((a, b) => a * 100 + b);
이 문제에서 굳이 time을 Number로 변경할 필요가 있을까요?
string 상태에서도 충분히 비교가 될 것 같아요!!

2023-05-26 16:46 UTC, h-beeen requested changes
브랜치 머지 후 커밋을 날리셔야, 수정사항만 반영됩니다.

2023-05-28 10:28 UTC, HyeonJeong519 commented on 현호/7주차_1620.js
> +    else // number일 경우
배열로 선언하는거 말고 map을 두개 선언해서 숫자, 이름 받는거 하나 이름, 숫자 하나 해서 처리하는 방법도 있습니당 고려해보세요!

2023-07-07 07:49 UTC, merged