[3주차] 스터디 코드 - 주현
h-beeen/Arcade42 pull request #94
Opened 2023-03-09 15:48 UTC by rnawlsgk

불 - 05427 풀이 중
주석 추가 예정

2023-03-10 06:14 UTC, h-beeen requested changes
.gitignore파일에 .gitignoreg 오탈자 있어, 반영되지 않았습니다.
수정 부탁드립니다.

2023-03-10 14:38 UTC, rnawlsgk commented
> 

수정 완료

2023-03-12 07:08 UTC, h-beeen approved these changes
Not Git Conflict

2023-03-12 12:40 UTC, SWARVY reviewed
전체적으로 코드를 이해하는데 어렵지 않았던 것 같아요, 황현정 리뷰에도 달아놨는데
prettier나 ESLint 써보시는 것 추천드립니다. 아마 플러그인에 있을거에요
[Lint in JAVA](https://nauni.tistory.com/m/275)

2023-03-12 12:40 UTC, SWARVY commented on 최주현/3주차_01926.java
> +        vis[start.x][start.y] = true;
```suggestion
        visited[start.x][start.y] = true;
```
vis 보다는 visited, 혹은 visit이 조금 더 직관적일 것 같아요

2023-03-12 12:40 UTC, SWARVY commented on 최주현/3주차_01926.java
> +        int count = 0; //각 그림의 넓이를 저장하는 변수
```suggestion
        int size = 0; //각 그림의 넓이를 저장하는 변수
```
넓이를 저장한다면 size 같은 친구들이 조금 더 좋을듯 해요
변수명 정하기가 워낙 귀찮으니 유용한 링크 드립니다 [변수명 생성기](http://curioustore.com/)

2023-03-12 12:40 UTC, SWARVY commented on 최주현/3주차_05427_실패.java
> +//이하 코드는 그냥 bfs틀만 잡혀있다. 나중에 다시 풀때 입력부분 참고 예정
불과 상근이의 움직임에서 중요한 건, 상근이의 움직임에 depth를 정해놓고
같은 depth에서는 불이 한번만 옮겨붙어야 한다는 아이디어가 제일 중요합니다! 해당 부분에 맞춰서 구현하시면 풀 수 있을 듯 해요

2023-03-12 12:40 UTC, SWARVY commented on 최주현/3주차_07576.java
> +    }
토마토를 입력할 때 count를 세줬다면 n^2의 작업은 굳이 할 필요가 없었을 것 같네요..!

2023-03-13 03:56 UTC, merged